server:
  port: 9004
  servlet:
    context-path: /

spring:
  application:
    name: ithome-article
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ithome_article?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: icql
    default-auto-commit: true
    auto-commit: true
    maximum-pool-size: 100
    max-idle: 10
    max-wait: 1000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
    minEvictableIdleTimeMillis: 300000
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: false
  redis:
    host: 188.188.0.0
  data:
    mongodb:
      host: 192.168.184.134
      port: 1111
      database: spitdb

logging:
  level:
    root: INFO
  #file: ithome-article.log