server:
  port: 8080
  servlet:
    context-path: /

dubbo:
  registry:
    address: localhost:2181,localhost:2182,localhost:2183
    protocol: zookeeper
  application:
    id: consumer
    name: consumer
    owner: icql

logging:
  level:
    root: INFO
  #file: consumer.log